INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('1', '1101', 'KABUPATEN SIMEULUE', '11');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('2', '1102', 'KABUPATEN ACEH SINGKIL', '11');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('3', '1103', 'KABUPATEN ACEH SELATAN', '11');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('4', '1104', 'KABUPATEN ACEH TENGGARA', '11');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('5', '1105', 'KABUPATEN ACEH TIMUR', '11');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('6', '1106', 'KABUPATEN ACEH TENGAH', '11');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('7', '1107', 'KABUPATEN ACEH BARAT', '11');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('8', '1108', 'KABUPATEN ACEH BESAR', '11');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('9', '1109', 'KABUPATEN PIDIE', '11');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('10', '1110', 'KABUPATEN BIREUEN', '11');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('11', '1111', 'KABUPATEN ACEH UTARA', '11');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('12', '1112', 'KABUPATEN ACEH BARAT DAYA', '11');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('13', '1113', 'KABUPATEN GAYO LUES', '11');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('14', '1114', 'KABUPATEN ACEH TAMIANG', '11');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('15', '1115', 'KABUPATEN NAGAN RAYA', '11');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('16', '1116', 'KABUPATEN ACEH JAYA', '11');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('17', '1117', 'KABUPATEN BENER MERIAH', '11');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('18', '1118', 'KABUPATEN PIDIE JAYA', '11');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('19', '1171', 'KOTA BANDA ACEH', '11');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('20', '1172', 'KOTA SABANG', '11');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('21', '1173', 'KOTA LANGSA', '11');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('22', '1174', 'KOTA LHOKSEUMAWE', '11');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('23', '1175', 'KOTA SUBULUSSALAM', '11');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('24', '1201', 'KABUPATEN NIAS', '12');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('25', '1202', 'KABUPATEN MANDAILING NATAL', '12');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('26', '1203', 'KABUPATEN TAPANULI SELATAN', '12');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('27', '1204', 'KABUPATEN TAPANULI TENGAH', '12');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('28', '1205', 'KABUPATEN TAPANULI UTARA', '12');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('29', '1206', 'KABUPATEN TOBA SAMOSIR', '12');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('30', '1207', 'KABUPATEN LABUHAN BATU', '12');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('31', '1208', 'KABUPATEN ASAHAN', '12');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('32', '1209', 'KABUPATEN SIMALUNGUN', '12');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('33', '1210', 'KABUPATEN DAIRI', '12');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('34', '1211', 'KABUPATEN KARO', '12');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('35', '1212', 'KABUPATEN DELI SERDANG', '12');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('36', '1213', 'KABUPATEN LANGKAT', '12');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('37', '1214', 'KABUPATEN NIAS SELATAN', '12');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('38', '1215', 'KABUPATEN HUMBANG HASUNDUTAN', '12');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('39', '1216', 'KABUPATEN PAKPAK BHARAT', '12');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('40', '1217', 'KABUPATEN SAMOSIR', '12');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('41', '1218', 'KABUPATEN SERDANG BEDAGAI', '12');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('42', '1219', 'KABUPATEN BATU BARA', '12');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('43', '1220', 'KABUPATEN PADANG LAWAS UTARA', '12');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('44', '1221', 'KABUPATEN PADANG LAWAS', '12');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('45', '1222', 'KABUPATEN LABUHAN BATU SELATAN', '12');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('46', '1223', 'KABUPATEN LABUHAN BATU UTARA', '12');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('47', '1224', 'KABUPATEN NIAS UTARA', '12');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('48', '1225', 'KABUPATEN NIAS BARAT', '12');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('49', '1271', 'KOTA SIBOLGA', '12');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('50', '1272', 'KOTA TANJUNG BALAI', '12');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('51', '1273', 'KOTA PEMATANG SIANTAR', '12');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('52', '1274', 'KOTA TEBING TINGGI', '12');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('53', '1275', 'KOTA MEDAN', '12');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('54', '1276', 'KOTA BINJAI', '12');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('55', '1277', 'KOTA PADANGSIDIMPUAN', '12');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('56', '1278', 'KOTA GUNUNGSITOLI', '12');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('57', '1301', 'KABUPATEN KEPULAUAN MENTAWAI', '13');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('58', '1302', 'KABUPATEN PESISIR SELATAN', '13');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('59', '1303', 'KABUPATEN SOLOK', '13');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('60', '1304', 'KABUPATEN SIJUNJUNG', '13');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('61', '1305', 'KABUPATEN TANAH DATAR', '13');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('62', '1306', 'KABUPATEN PADANG PARIAMAN', '13');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('63', '1307', 'KABUPATEN AGAM', '13');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('64', '1308', 'KABUPATEN LIMA PULUH KOTA', '13');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('65', '1309', 'KABUPATEN PASAMAN', '13');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('66', '1310', 'KABUPATEN SOLOK SELATAN', '13');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('67', '1311', 'KABUPATEN DHARMASRAYA', '13');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('68', '1312', 'KABUPATEN PASAMAN BARAT', '13');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('69', '1371', 'KOTA PADANG', '13');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('70', '1372', 'KOTA SOLOK', '13');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('71', '1373', 'KOTA SAWAH LUNTO', '13');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('72', '1374', 'KOTA PADANG PANJANG', '13');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('73', '1375', 'KOTA BUKITTINGGI', '13');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('74', '1376', 'KOTA PAYAKUMBUH', '13');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('75', '1377', 'KOTA PARIAMAN', '13');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('76', '1401', 'KABUPATEN KUANTAN SINGINGI', '14');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('77', '1402', 'KABUPATEN INDRAGIRI HULU', '14');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('78', '1403', 'KABUPATEN INDRAGIRI HILIR', '14');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('79', '1404', 'KABUPATEN PELALAWAN', '14');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('80', '1405', 'KABUPATEN S I A K', '14');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('81', '1406', 'KABUPATEN KAMPAR', '14');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('82', '1407', 'KABUPATEN ROKAN HULU', '14');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('83', '1408', 'KABUPATEN BENGKALIS', '14');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('84', '1409', 'KABUPATEN ROKAN HILIR', '14');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('85', '1410', 'KABUPATEN KEPULAUAN MERANTI', '14');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('86', '1471', 'KOTA PEKANBARU', '14');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('87', '1473', 'KOTA D U M A I', '14');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('88', '1501', 'KABUPATEN KERINCI', '15');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('89', '1502', 'KABUPATEN MERANGIN', '15');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('90', '1503', 'KABUPATEN SAROLANGUN', '15');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('91', '1504', 'KABUPATEN BATANG HARI', '15');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('92', '1505', 'KABUPATEN MUARO JAMBI', '15');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('93', '1506', 'KABUPATEN TANJUNG JABUNG TIMUR', '15');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('94', '1507', 'KABUPATEN TANJUNG JABUNG BARAT', '15');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('95', '1508', 'KABUPATEN TEBO', '15');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('96', '1509', 'KABUPATEN BUNGO', '15');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('97', '1571', 'KOTA JAMBI', '15');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('98', '1572', 'KOTA SUNGAI PENUH', '15');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('99', '1601', 'KABUPATEN OGAN KOMERING ULU', '16');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('100', '1602', 'KABUPATEN OGAN KOMERING ILIR', '16');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('101', '1603', 'KABUPATEN MUARA ENIM', '16');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('102', '1604', 'KABUPATEN LAHAT', '16');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('103', '1605', 'KABUPATEN MUSI RAWAS', '16');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('104', '1606', 'KABUPATEN MUSI BANYUASIN', '16');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('105', '1607', 'KABUPATEN BANYU ASIN', '16');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('106', '1608', 'KABUPATEN OGAN KOMERING ULU SELATAN', '16');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('107', '1609', 'KABUPATEN OGAN KOMERING ULU TIMUR', '16');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('108', '1610', 'KABUPATEN OGAN ILIR', '16');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('109', '1611', 'KABUPATEN EMPAT LAWANG', '16');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('110', '1612', 'KABUPATEN PENUKAL ABAB LEMATANG ILIR', '16');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('111', '1613', 'KABUPATEN MUSI RAWAS UTARA', '16');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('112', '1671', 'KOTA PALEMBANG', '16');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('113', '1672', 'KOTA PRABUMULIH', '16');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('114', '1673', 'KOTA PAGAR ALAM', '16');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('115', '1674', 'KOTA LUBUKLINGGAU', '16');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('116', '1701', 'KABUPATEN BENGKULU SELATAN', '17');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('117', '1702', 'KABUPATEN REJANG LEBONG', '17');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('118', '1703', 'KABUPATEN BENGKULU UTARA', '17');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('119', '1704', 'KABUPATEN KAUR', '17');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('120', '1705', 'KABUPATEN SELUMA', '17');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('121', '1706', 'KABUPATEN MUKOMUKO', '17');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('122', '1707', 'KABUPATEN LEBONG', '17');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('123', '1708', 'KABUPATEN KEPAHIANG', '17');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('124', '1709', 'KABUPATEN BENGKULU TENGAH', '17');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('125', '1771', 'KOTA BENGKULU', '17');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('126', '1801', 'KABUPATEN LAMPUNG BARAT', '18');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('127', '1802', 'KABUPATEN TANGGAMUS', '18');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('128', '1803', 'KABUPATEN LAMPUNG SELATAN', '18');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('129', '1804', 'KABUPATEN LAMPUNG TIMUR', '18');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('130', '1805', 'KABUPATEN LAMPUNG TENGAH', '18');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('131', '1806', 'KABUPATEN LAMPUNG UTARA', '18');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('132', '1807', 'KABUPATEN WAY KANAN', '18');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('133', '1808', 'KABUPATEN TULANGBAWANG', '18');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('134', '1809', 'KABUPATEN PESAWARAN', '18');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('135', '1810', 'KABUPATEN PRINGSEWU', '18');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('136', '1811', 'KABUPATEN MESUJI', '18');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('137', '1812', 'KABUPATEN TULANG BAWANG BARAT', '18');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('138', '1813', 'KABUPATEN PESISIR BARAT', '18');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('139', '1871', 'KOTA BANDAR LAMPUNG', '18');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('140', '1872', 'KOTA METRO', '18');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('141', '1901', 'KABUPATEN BANGKA', '19');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('142', '1902', 'KABUPATEN BELITUNG', '19');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('143', '1903', 'KABUPATEN BANGKA BARAT', '19');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('144', '1904', 'KABUPATEN BANGKA TENGAH', '19');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('145', '1905', 'KABUPATEN BANGKA SELATAN', '19');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('146', '1906', 'KABUPATEN BELITUNG TIMUR', '19');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('147', '1971', 'KOTA PANGKAL PINANG', '19');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('148', '2101', 'KABUPATEN KARIMUN', '21');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('149', '2102', 'KABUPATEN BINTAN', '21');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('150', '2103', 'KABUPATEN NATUNA', '21');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('151', '2104', 'KABUPATEN LINGGA', '21');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('152', '2105', 'KABUPATEN KEPULAUAN ANAMBAS', '21');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('153', '2171', 'KOTA B A T A M', '21');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('154', '2172', 'KOTA TANJUNG PINANG', '21');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('155', '3101', 'KABUPATEN KEPULAUAN SERIBU', '31');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('156', '3171', 'KOTA JAKARTA SELATAN', '31');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('157', '3172', 'KOTA JAKARTA TIMUR', '31');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('158', '3173', 'KOTA JAKARTA PUSAT', '31');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('159', '3174', 'KOTA JAKARTA BARAT', '31');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('160', '3175', 'KOTA JAKARTA UTARA', '31');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('161', '3201', 'KABUPATEN BOGOR', '32');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('162', '3202', 'KABUPATEN SUKABUMI', '32');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('163', '3203', 'KABUPATEN CIANJUR', '32');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('164', '3204', 'KABUPATEN BANDUNG', '32');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('165', '3205', 'KABUPATEN GARUT', '32');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('166', '3206', 'KABUPATEN TASIKMALAYA', '32');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('167', '3207', 'KABUPATEN CIAMIS', '32');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('168', '3208', 'KABUPATEN KUNINGAN', '32');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('169', '3209', 'KABUPATEN CIREBON', '32');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('170', '3210', 'KABUPATEN MAJALENGKA', '32');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('171', '3211', 'KABUPATEN SUMEDANG', '32');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('172', '3212', 'KABUPATEN INDRAMAYU', '32');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('173', '3213', 'KABUPATEN SUBANG', '32');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('174', '3214', 'KABUPATEN PURWAKARTA', '32');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('175', '3215', 'KABUPATEN KARAWANG', '32');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('176', '3216', 'KABUPATEN BEKASI', '32');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('177', '3217', 'KABUPATEN BANDUNG BARAT', '32');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('178', '3218', 'KABUPATEN PANGANDARAN', '32');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('179', '3271', 'KOTA BOGOR', '32');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('180', '3272', 'KOTA SUKABUMI', '32');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('181', '3273', 'KOTA BANDUNG', '32');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('182', '3274', 'KOTA CIREBON', '32');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('183', '3275', 'KOTA BEKASI', '32');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('184', '3276', 'KOTA DEPOK', '32');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('185', '3277', 'KOTA CIMAHI', '32');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('186', '3278', 'KOTA TASIKMALAYA', '32');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('187', '3279', 'KOTA BANJAR', '32');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('188', '3301', 'KABUPATEN CILACAP', '33');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('189', '3302', 'KABUPATEN BANYUMAS', '33');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('190', '3303', 'KABUPATEN PURBALINGGA', '33');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('191', '3304', 'KABUPATEN BANJARNEGARA', '33');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('192', '3305', 'KABUPATEN KEBUMEN', '33');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('193', '3306', 'KABUPATEN PURWOREJO', '33');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('194', '3307', 'KABUPATEN WONOSOBO', '33');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('195', '3308', 'KABUPATEN MAGELANG', '33');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('196', '3309', 'KABUPATEN BOYOLALI', '33');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('197', '3310', 'KABUPATEN KLATEN', '33');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('198', '3311', 'KABUPATEN SUKOHARJO', '33');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('199', '3312', 'KABUPATEN WONOGIRI', '33');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('200', '3313', 'KABUPATEN KARANGANYAR', '33');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('201', '3314', 'KABUPATEN SRAGEN', '33');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('202', '3315', 'KABUPATEN GROBOGAN', '33');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('203', '3316', 'KABUPATEN BLORA', '33');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('204', '3317', 'KABUPATEN REMBANG', '33');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('205', '3318', 'KABUPATEN PATI', '33');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('206', '3319', 'KABUPATEN KUDUS', '33');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('207', '3320', 'KABUPATEN JEPARA', '33');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('208', '3321', 'KABUPATEN DEMAK', '33');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('209', '3322', 'KABUPATEN SEMARANG', '33');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('210', '3323', 'KABUPATEN TEMANGGUNG', '33');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('211', '3324', 'KABUPATEN KENDAL', '33');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('212', '3325', 'KABUPATEN BATANG', '33');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('213', '3326', 'KABUPATEN PEKALONGAN', '33');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('214', '3327', 'KABUPATEN PEMALANG', '33');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('215', '3328', 'KABUPATEN TEGAL', '33');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('216', '3329', 'KABUPATEN BREBES', '33');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('217', '3371', 'KOTA MAGELANG', '33');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('218', '3372', 'KOTA SURAKARTA', '33');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('219', '3373', 'KOTA SALATIGA', '33');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('220', '3374', 'KOTA SEMARANG', '33');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('221', '3375', 'KOTA PEKALONGAN', '33');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('222', '3376', 'KOTA TEGAL', '33');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('223', '3401', 'KABUPATEN KULON PROGO', '34');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('224', '3402', 'KABUPATEN BANTUL', '34');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('225', '3403', 'KABUPATEN GUNUNG KIDUL', '34');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('226', '3404', 'KABUPATEN SLEMAN', '34');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('227', '3471', 'KOTA YOGYAKARTA', '34');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('228', '3501', 'KABUPATEN PACITAN', '35');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('229', '3502', 'KABUPATEN PONOROGO', '35');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('230', '3503', 'KABUPATEN TRENGGALEK', '35');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('231', '3504', 'KABUPATEN TULUNGAGUNG', '35');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('232', '3505', 'KABUPATEN BLITAR', '35');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('233', '3506', 'KABUPATEN KEDIRI', '35');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('234', '3507', 'KABUPATEN MALANG', '35');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('235', '3508', 'KABUPATEN LUMAJANG', '35');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('236', '3509', 'KABUPATEN JEMBER', '35');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('237', '3510', 'KABUPATEN BANYUWANGI', '35');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('238', '3511', 'KABUPATEN BONDOWOSO', '35');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('239', '3512', 'KABUPATEN SITUBONDO', '35');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('240', '3513', 'KABUPATEN PROBOLINGGO', '35');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('241', '3514', 'KABUPATEN PASURUAN', '35');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('242', '3515', 'KABUPATEN SIDOARJO', '35');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('243', '3516', 'KABUPATEN MOJOKERTO', '35');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('244', '3517', 'KABUPATEN JOMBANG', '35');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('245', '3518', 'KABUPATEN NGANJUK', '35');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('246', '3519', 'KABUPATEN MADIUN', '35');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('247', '3520', 'KABUPATEN MAGETAN', '35');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('248', '3521', 'KABUPATEN NGAWI', '35');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('249', '3522', 'KABUPATEN BOJONEGORO', '35');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('250', '3523', 'KABUPATEN TUBAN', '35');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('251', '3524', 'KABUPATEN LAMONGAN', '35');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('252', '3525', 'KABUPATEN GRESIK', '35');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('253', '3526', 'KABUPATEN BANGKALAN', '35');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('254', '3527', 'KABUPATEN SAMPANG', '35');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('255', '3528', 'KABUPATEN PAMEKASAN', '35');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('256', '3529', 'KABUPATEN SUMENEP', '35');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('257', '3571', 'KOTA KEDIRI', '35');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('258', '3572', 'KOTA BLITAR', '35');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('259', '3573', 'KOTA MALANG', '35');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('260', '3574', 'KOTA PROBOLINGGO', '35');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('261', '3575', 'KOTA PASURUAN', '35');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('262', '3576', 'KOTA MOJOKERTO', '35');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('263', '3577', 'KOTA MADIUN', '35');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('264', '3578', 'KOTA SURABAYA', '35');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('265', '3579', 'KOTA BATU', '35');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('266', '3601', 'KABUPATEN PANDEGLANG', '36');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('267', '3602', 'KABUPATEN LEBAK', '36');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('268', '3603', 'KABUPATEN TANGERANG', '36');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('269', '3604', 'KABUPATEN SERANG', '36');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('270', '3671', 'KOTA TANGERANG', '36');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('271', '3672', 'KOTA CILEGON', '36');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('272', '3673', 'KOTA SERANG', '36');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('273', '3674', 'KOTA TANGERANG SELATAN', '36');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('274', '5101', 'KABUPATEN JEMBRANA', '51');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('275', '5102', 'KABUPATEN TABANAN', '51');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('276', '5103', 'KABUPATEN BADUNG', '51');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('277', '5104', 'KABUPATEN GIANYAR', '51');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('278', '5105', 'KABUPATEN KLUNGKUNG', '51');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('279', '5106', 'KABUPATEN BANGLI', '51');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('280', '5107', 'KABUPATEN KARANG ASEM', '51');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('281', '5108', 'KABUPATEN BULELENG', '51');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('282', '5171', 'KOTA DENPASAR', '51');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('283', '5201', 'KABUPATEN LOMBOK BARAT', '52');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('284', '5202', 'KABUPATEN LOMBOK TENGAH', '52');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('285', '5203', 'KABUPATEN LOMBOK TIMUR', '52');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('286', '5204', 'KABUPATEN SUMBAWA', '52');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('287', '5205', 'KABUPATEN DOMPU', '52');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('288', '5206', 'KABUPATEN BIMA', '52');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('289', '5207', 'KABUPATEN SUMBAWA BARAT', '52');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('290', '5208', 'KABUPATEN LOMBOK UTARA', '52');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('291', '5271', 'KOTA MATARAM', '52');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('292', '5272', 'KOTA BIMA', '52');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('293', '5301', 'KABUPATEN SUMBA BARAT', '53');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('294', '5302', 'KABUPATEN SUMBA TIMUR', '53');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('295', '5303', 'KABUPATEN KUPANG', '53');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('296', '5304', 'KABUPATEN TIMOR TENGAH SELATAN', '53');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('297', '5305', 'KABUPATEN TIMOR TENGAH UTARA', '53');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('298', '5306', 'KABUPATEN BELU', '53');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('299', '5307', 'KABUPATEN ALOR', '53');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('300', '5308', 'KABUPATEN LEMBATA', '53');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('301', '5309', 'KABUPATEN FLORES TIMUR', '53');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('302', '5310', 'KABUPATEN SIKKA', '53');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('303', '5311', 'KABUPATEN ENDE', '53');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('304', '5312', 'KABUPATEN NGADA', '53');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('305', '5313', 'KABUPATEN MANGGARAI', '53');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('306', '5314', 'KABUPATEN ROTE NDAO', '53');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('307', '5315', 'KABUPATEN MANGGARAI BARAT', '53');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('308', '5316', 'KABUPATEN SUMBA TENGAH', '53');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('309', '5317', 'KABUPATEN SUMBA BARAT DAYA', '53');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('310', '5318', 'KABUPATEN NAGEKEO', '53');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('311', '5319', 'KABUPATEN MANGGARAI TIMUR', '53');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('312', '5320', 'KABUPATEN SABU RAIJUA', '53');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('313', '5321', 'KABUPATEN MALAKA', '53');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('314', '5371', 'KOTA KUPANG', '53');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('315', '6101', 'KABUPATEN SAMBAS', '61');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('316', '6102', 'KABUPATEN BENGKAYANG', '61');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('317', '6103', 'KABUPATEN LANDAK', '61');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('318', '6104', 'KABUPATEN MEMPAWAH', '61');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('319', '6105', 'KABUPATEN SANGGAU', '61');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('320', '6106', 'KABUPATEN KETAPANG', '61');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('321', '6107', 'KABUPATEN SINTANG', '61');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('322', '6108', 'KABUPATEN KAPUAS HULU', '61');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('323', '6109', 'KABUPATEN SEKADAU', '61');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('324', '6110', 'KABUPATEN MELAWI', '61');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('325', '6111', 'KABUPATEN KAYONG UTARA', '61');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('326', '6112', 'KABUPATEN KUBU RAYA', '61');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('327', '6171', 'KOTA PONTIANAK', '61');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('328', '6172', 'KOTA SINGKAWANG', '61');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('329', '6201', 'KABUPATEN KOTAWARINGIN BARAT', '62');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('330', '6202', 'KABUPATEN KOTAWARINGIN TIMUR', '62');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('331', '6203', 'KABUPATEN KAPUAS', '62');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('332', '6204', 'KABUPATEN BARITO SELATAN', '62');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('333', '6205', 'KABUPATEN BARITO UTARA', '62');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('334', '6206', 'KABUPATEN SUKAMARA', '62');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('335', '6207', 'KABUPATEN LAMANDAU', '62');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('336', '6208', 'KABUPATEN SERUYAN', '62');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('337', '6209', 'KABUPATEN KATINGAN', '62');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('338', '6210', 'KABUPATEN PULANG PISAU', '62');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('339', '6211', 'KABUPATEN GUNUNG MAS', '62');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('340', '6212', 'KABUPATEN BARITO TIMUR', '62');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('341', '6213', 'KABUPATEN MURUNG RAYA', '62');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('342', '6271', 'KOTA PALANGKA RAYA', '62');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('343', '6301', 'KABUPATEN TANAH LAUT', '63');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('344', '6302', 'KABUPATEN KOTA BARU', '63');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('345', '6303', 'KABUPATEN BANJAR', '63');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('346', '6304', 'KABUPATEN BARITO KUALA', '63');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('347', '6305', 'KABUPATEN TAPIN', '63');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('348', '6306', 'KABUPATEN HULU SUNGAI SELATAN', '63');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('349', '6307', 'KABUPATEN HULU SUNGAI TENGAH', '63');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('350', '6308', 'KABUPATEN HULU SUNGAI UTARA', '63');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('351', '6309', 'KABUPATEN TABALONG', '63');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('352', '6310', 'KABUPATEN TANAH BUMBU', '63');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('353', '6311', 'KABUPATEN BALANGAN', '63');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('354', '6371', 'KOTA BANJARMASIN', '63');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('355', '6372', 'KOTA BANJAR BARU', '63');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('356', '6401', 'KABUPATEN PASER', '64');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('357', '6402', 'KABUPATEN KUTAI BARAT', '64');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('358', '6403', 'KABUPATEN KUTAI KARTANEGARA', '64');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('359', '6404', 'KABUPATEN KUTAI TIMUR', '64');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('360', '6405', 'KABUPATEN BERAU', '64');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('361', '6409', 'KABUPATEN PENAJAM PASER UTARA', '64');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('362', '6411', 'KABUPATEN MAHAKAM HULU', '64');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('363', '6471', 'KOTA BALIKPAPAN', '64');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('364', '6472', 'KOTA SAMARINDA', '64');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('365', '6474', 'KOTA BONTANG', '64');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('366', '6501', 'KABUPATEN MALINAU', '65');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('367', '6502', 'KABUPATEN BULUNGAN', '65');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('368', '6503', 'KABUPATEN TANA TIDUNG', '65');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('369', '6504', 'KABUPATEN NUNUKAN', '65');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('370', '6571', 'KOTA TARAKAN', '65');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('371', '7101', 'KABUPATEN BOLAANG MONGONDOW', '71');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('372', '7102', 'KABUPATEN MINAHASA', '71');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('373', '7103', 'KABUPATEN KEPULAUAN SANGIHE', '71');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('374', '7104', 'KABUPATEN KEPULAUAN TALAUD', '71');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('375', '7105', 'KABUPATEN MINAHASA SELATAN', '71');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('376', '7106', 'KABUPATEN MINAHASA UTARA', '71');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('377', '7107', 'KABUPATEN BOLAANG MONGONDOW UTARA', '71');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('378', '7108', 'KABUPATEN SIAU TAGULANDANG BIARO', '71');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('379', '7109', 'KABUPATEN MINAHASA TENGGARA', '71');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('380', '7110', 'KABUPATEN BOLAANG MONGONDOW SELATAN', '71');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('381', '7111', 'KABUPATEN BOLAANG MONGONDOW TIMUR', '71');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('382', '7171', 'KOTA MANADO', '71');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('383', '7172', 'KOTA BITUNG', '71');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('384', '7173', 'KOTA TOMOHON', '71');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('385', '7174', 'KOTA KOTAMOBAGU', '71');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('386', '7201', 'KABUPATEN BANGGAI KEPULAUAN', '72');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('387', '7202', 'KABUPATEN BANGGAI', '72');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('388', '7203', 'KABUPATEN MOROWALI', '72');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('389', '7204', 'KABUPATEN POSO', '72');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('390', '7205', 'KABUPATEN DONGGALA', '72');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('391', '7206', 'KABUPATEN TOLI-TOLI', '72');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('392', '7207', 'KABUPATEN BUOL', '72');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('393', '7208', 'KABUPATEN PARIGI MOUTONG', '72');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('394', '7209', 'KABUPATEN TOJO UNA-UNA', '72');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('395', '7210', 'KABUPATEN SIGI', '72');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('396', '7211', 'KABUPATEN BANGGAI LAUT', '72');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('397', '7212', 'KABUPATEN MOROWALI UTARA', '72');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('398', '7271', 'KOTA PALU', '72');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('399', '7301', 'KABUPATEN KEPULAUAN SELAYAR', '73');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('400', '7302', 'KABUPATEN BULUKUMBA', '73');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('401', '7303', 'KABUPATEN BANTAENG', '73');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('402', '7304', 'KABUPATEN JENEPONTO', '73');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('403', '7305', 'KABUPATEN TAKALAR', '73');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('404', '7306', 'KABUPATEN GOWA', '73');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('405', '7307', 'KABUPATEN SINJAI', '73');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('406', '7308', 'KABUPATEN MAROS', '73');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('407', '7309', 'KABUPATEN PANGKAJENE DAN KEPULAUAN', '73');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('408', '7310', 'KABUPATEN BARRU', '73');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('409', '7311', 'KABUPATEN BONE', '73');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('410', '7312', 'KABUPATEN SOPPENG', '73');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('411', '7313', 'KABUPATEN WAJO', '73');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('412', '7314', 'KABUPATEN SIDENRENG RAPPANG', '73');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('413', '7315', 'KABUPATEN PINRANG', '73');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('414', '7316', 'KABUPATEN ENREKANG', '73');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('415', '7317', 'KABUPATEN LUWU', '73');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('416', '7318', 'KABUPATEN TANA TORAJA', '73');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('417', '7322', 'KABUPATEN LUWU UTARA', '73');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('418', '7325', 'KABUPATEN LUWU TIMUR', '73');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('419', '7326', 'KABUPATEN TORAJA UTARA', '73');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('420', '7371', 'KOTA MAKASSAR', '73');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('421', '7372', 'KOTA PAREPARE', '73');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('422', '7373', 'KOTA PALOPO', '73');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('423', '7401', 'KABUPATEN BUTON', '74');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('424', '7402', 'KABUPATEN MUNA', '74');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('425', '7403', 'KABUPATEN KONAWE', '74');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('426', '7404', 'KABUPATEN KOLAKA', '74');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('427', '7405', 'KABUPATEN KONAWE SELATAN', '74');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('428', '7406', 'KABUPATEN BOMBANA', '74');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('429', '7407', 'KABUPATEN WAKATOBI', '74');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('430', '7408', 'KABUPATEN KOLAKA UTARA', '74');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('431', '7409', 'KABUPATEN BUTON UTARA', '74');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('432', '7410', 'KABUPATEN KONAWE UTARA', '74');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('433', '7411', 'KABUPATEN KOLAKA TIMUR', '74');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('434', '7412', 'KABUPATEN KONAWE KEPULAUAN', '74');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('435', '7413', 'KABUPATEN MUNA BARAT', '74');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('436', '7414', 'KABUPATEN BUTON TENGAH', '74');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('437', '7415', 'KABUPATEN BUTON SELATAN', '74');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('438', '7471', 'KOTA KENDARI', '74');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('439', '7472', 'KOTA BAUBAU', '74');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('440', '7501', 'KABUPATEN BOALEMO', '75');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('441', '7502', 'KABUPATEN GORONTALO', '75');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('442', '7503', 'KABUPATEN POHUWATO', '75');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('443', '7504', 'KABUPATEN BONE BOLANGO', '75');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('444', '7505', 'KABUPATEN GORONTALO UTARA', '75');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('445', '7571', 'KOTA GORONTALO', '75');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('446', '7601', 'KABUPATEN MAJENE', '76');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('447', '7602', 'KABUPATEN POLEWALI MANDAR', '76');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('448', '7603', 'KABUPATEN MAMASA', '76');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('449', '7604', 'KABUPATEN MAMUJU', '76');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('450', '7605', 'KABUPATEN MAMUJU UTARA', '76');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('451', '7606', 'KABUPATEN MAMUJU TENGAH', '76');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('452', '8101', 'KABUPATEN MALUKU TENGGARA BARAT', '81');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('453', '8102', 'KABUPATEN MALUKU TENGGARA', '81');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('454', '8103', 'KABUPATEN MALUKU TENGAH', '81');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('455', '8104', 'KABUPATEN BURU', '81');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('456', '8105', 'KABUPATEN KEPULAUAN ARU', '81');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('457', '8106', 'KABUPATEN SERAM BAGIAN BARAT', '81');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('458', '8107', 'KABUPATEN SERAM BAGIAN TIMUR', '81');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('459', '8108', 'KABUPATEN MALUKU BARAT DAYA', '81');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('460', '8109', 'KABUPATEN BURU SELATAN', '81');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('461', '8171', 'KOTA AMBON', '81');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('462', '8172', 'KOTA TUAL', '81');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('463', '8201', 'KABUPATEN HALMAHERA BARAT', '82');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('464', '8202', 'KABUPATEN HALMAHERA TENGAH', '82');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('465', '8203', 'KABUPATEN KEPULAUAN SULA', '82');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('466', '8204', 'KABUPATEN HALMAHERA SELATAN', '82');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('467', '8205', 'KABUPATEN HALMAHERA UTARA', '82');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('468', '8206', 'KABUPATEN HALMAHERA TIMUR', '82');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('469', '8207', 'KABUPATEN PULAU MOROTAI', '82');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('470', '8208', 'KABUPATEN PULAU TALIABU', '82');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('471', '8271', 'KOTA TERNATE', '82');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('472', '8272', 'KOTA TIDORE KEPULAUAN', '82');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('473', '9101', 'KABUPATEN FAKFAK', '91');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('474', '9102', 'KABUPATEN KAIMANA', '91');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('475', '9103', 'KABUPATEN TELUK WONDAMA', '91');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('476', '9104', 'KABUPATEN TELUK BINTUNI', '91');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('477', '9105', 'KABUPATEN MANOKWARI', '91');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('478', '9106', 'KABUPATEN SORONG SELATAN', '91');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('479', '9107', 'KABUPATEN SORONG', '91');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('480', '9108', 'KABUPATEN RAJA AMPAT', '91');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('481', '9109', 'KABUPATEN TAMBRAUW', '91');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('482', '9110', 'KABUPATEN MAYBRAT', '91');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('483', '9111', 'KABUPATEN MANOKWARI SELATAN', '91');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('484', '9112', 'KABUPATEN PEGUNUNGAN ARFAK', '91');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('485', '9171', 'KOTA SORONG', '91');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('486', '9401', 'KABUPATEN MERAUKE', '94');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('487', '9402', 'KABUPATEN JAYAWIJAYA', '94');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('488', '9403', 'KABUPATEN JAYAPURA', '94');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('489', '9404', 'KABUPATEN NABIRE', '94');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('490', '9408', 'KABUPATEN KEPULAUAN YAPEN', '94');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('491', '9409', 'KABUPATEN BIAK NUMFOR', '94');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('492', '9410', 'KABUPATEN PANIAI', '94');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('493', '9411', 'KABUPATEN PUNCAK JAYA', '94');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('494', '9412', 'KABUPATEN MIMIKA', '94');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('495', '9413', 'KABUPATEN BOVEN DIGOEL', '94');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('496', '9414', 'KABUPATEN MAPPI', '94');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('497', '9415', 'KABUPATEN ASMAT', '94');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('498', '9416', 'KABUPATEN YAHUKIMO', '94');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('499', '9417', 'KABUPATEN PEGUNUNGAN BINTANG', '94');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('500', '9418', 'KABUPATEN TOLIKARA', '94');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('501', '9419', 'KABUPATEN SARMI', '94');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('502', '9420', 'KABUPATEN KEEROM', '94');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('503', '9426', 'KABUPATEN WAROPEN', '94');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('504', '9427', 'KABUPATEN SUPIORI', '94');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('505', '9428', 'KABUPATEN MAMBERAMO RAYA', '94');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('506', '9429', 'KABUPATEN NDUGA', '94');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('507', '9430', 'KABUPATEN LANNY JAYA', '94');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('508', '9431', 'KABUPATEN MAMBERAMO TENGAH', '94');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('509', '9432', 'KABUPATEN YALIMO', '94');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('510', '9433', 'KABUPATEN PUNCAK', '94');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('511', '9434', 'KABUPATEN DOGIYAI', '94');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('512', '9435', 'KABUPATEN INTAN JAYA', '94');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('513', '9436', 'KABUPATEN DEIYAI', '94');
INSERT INTO "kota"("id", "kode", "name", "kode_provinsi") VALUES ('514', '9471', 'KOTA JAYAPURA', '94');
