INSERT INTO "provinsi"("id", "kode", "name") VALUES ('1', '11', 'ACEH');
INSERT INTO "provinsi"("id", "kode", "name") VALUES ('2', '12', 'SUMATERA UTARA');
INSERT INTO "provinsi"("id", "kode", "name") VALUES ('3', '13', 'SUMATERA BARAT');
INSERT INTO "provinsi"("id", "kode", "name") VALUES ('4', '14', 'RIAU');
INSERT INTO "provinsi"("id", "kode", "name") VALUES ('5', '15', 'JAMBI');
INSERT INTO "provinsi"("id", "kode", "name") VALUES ('6', '16', 'SUMATERA SELATAN');
INSERT INTO "provinsi"("id", "kode", "name") VALUES ('7', '17', 'BENGKULU');
INSERT INTO "provinsi"("id", "kode", "name") VALUES ('8', '18', 'LAMPUNG');
INSERT INTO "provinsi"("id", "kode", "name") VALUES ('9', '19', 'KEPULAUAN BANGKA BELITUNG');
INSERT INTO "provinsi"("id", "kode", "name") VALUES ('10', '21', 'KEPULAUAN RIAU');
INSERT INTO "provinsi"("id", "kode", "name") VALUES ('11', '31', 'DKI JAKARTA');
INSERT INTO "provinsi"("id", "kode", "name") VALUES ('12', '32', 'JAWA BARAT');
INSERT INTO "provinsi"("id", "kode", "name") VALUES ('13', '33', 'JAWA TENGAH');
INSERT INTO "provinsi"("id", "kode", "name") VALUES ('14', '34', 'DI YOGYAKARTA');
INSERT INTO "provinsi"("id", "kode", "name") VALUES ('15', '35', 'JAWA TIMUR');
INSERT INTO "provinsi"("id", "kode", "name") VALUES ('16', '36', 'BANTEN');
INSERT INTO "provinsi"("id", "kode", "name") VALUES ('17', '51', 'BALI');
INSERT INTO "provinsi"("id", "kode", "name") VALUES ('18', '52', 'NUSA TENGGARA BARAT');
INSERT INTO "provinsi"("id", "kode", "name") VALUES ('19', '53', 'NUSA TENGGARA TIMUR');
INSERT INTO "provinsi"("id", "kode", "name") VALUES ('20', '61', 'KALIMANTAN BARAT');
INSERT INTO "provinsi"("id", "kode", "name") VALUES ('21', '62', 'KALIMANTAN TENGAH');
INSERT INTO "provinsi"("id", "kode", "name") VALUES ('22', '63', 'KALIMANTAN SELATAN');
INSERT INTO "provinsi"("id", "kode", "name") VALUES ('23', '64', 'KALIMANTAN TIMUR');
INSERT INTO "provinsi"("id", "kode", "name") VALUES ('24', '65', 'KALIMANTAN UTARA');
INSERT INTO "provinsi"("id", "kode", "name") VALUES ('25', '71', 'SULAWESI UTARA');
INSERT INTO "provinsi"("id", "kode", "name") VALUES ('26', '72', 'SULAWESI TENGAH');
INSERT INTO "provinsi"("id", "kode", "name") VALUES ('27', '73', 'SULAWESI SELATAN');
INSERT INTO "provinsi"("id", "kode", "name") VALUES ('28', '74', 'SULAWESI TENGGARA');
INSERT INTO "provinsi"("id", "kode", "name") VALUES ('29', '75', 'GORONTALO');
INSERT INTO "provinsi"("id", "kode", "name") VALUES ('30', '76', 'SULAWESI BARAT');
INSERT INTO "provinsi"("id", "kode", "name") VALUES ('31', '81', 'MALUKU');
INSERT INTO "provinsi"("id", "kode", "name") VALUES ('32', '82', 'MALUKU UTARA');
INSERT INTO "provinsi"("id", "kode", "name") VALUES ('33', '91', 'PAPUA BARAT');
INSERT INTO "provinsi"("id", "kode", "name") VALUES ('34', '94', 'PAPUA');
