INSERT INTO "sembako"("id", "nama", "satuan", "hargalama", "hargabaru") VALUES ('1', 'Beras', 'kg', '5000', '12000');
INSERT INTO "sembako"("id", "nama", "satuan", "hargalama", "hargabaru") VALUES ('2', 'Minyak ', 'liter', '7000', '10000');
INSERT INTO "sembako"("id", "nama", "satuan", "hargalama", "hargabaru") VALUES ('3', 'Gula', 'kg', '3000', '5000');
INSERT INTO "sembako"("id", "nama", "satuan", "hargalama", "hargabaru") VALUES ('4', 'Jagung', 'kg', '4000', '7000');
INSERT INTO "sembako"("id", "nama", "satuan", "hargalama", "hargabaru") VALUES ('5', 'Kedelai', 'kg', '2000', '3000');
INSERT INTO "sembako"("id", "nama", "satuan", "hargalama", "hargabaru") VALUES ('6', 'Kacang', 'kg', '12000', '4000');
INSERT INTO "sembako"("id", "nama", "satuan", "hargalama", "hargabaru") VALUES ('7', 'Garam', 'kg', '10000', '2000');
INSERT INTO "sembako"("id", "nama", "satuan", "hargalama", "hargabaru") VALUES ('8', 'Cabai', 'kg', '5000', '20000');
INSERT INTO "sembako"("id", "nama", "satuan", "hargalama", "hargabaru") VALUES ('9', 'Wortel', 'kg', '12000', '14000');
INSERT INTO "sembako"("id", "nama", "satuan", "hargalama", "hargabaru") VALUES ('10', 'Kentang', 'kg', '10000', '12000');
